import logo from "./images/logo.svg";
import user from "./images/icons/user.svg";
import pattern1 from "./images/pattern-1.svg";
import arrowTopRight from "./images/home/hero/arrow-top-right.svg";
import arrowPrimary from "./images/icons/tr-arrow-primary.svg";
import pmArrowLeft from "./images/icons/pm-arrow-left.svg";
import pmArrowRight from "./images/icons/pm-arrow-right.svg";
import footerImg from "./images/footer.jpg";
import arrowDown from "./images/icons/arrow-down.svg";
import quoteUp from "./images/home/testimonials/quote-up.svg";
import quoteDown from "./images/home/testimonials/quote-down.svg";
export const assets = { logo, user, pattern1, arrowTopRight, arrowPrimary, pmArrowLeft, pmArrowRight, footerImg, arrowDown, quoteUp, quoteDown };
