import mongoose from "mongoose";

const miceSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
        required:true
    },
    metaDescription:{
        type:String,
        required:true
    },
    firstSection:{
        mainTitle:{
            type:String,
            required:true
        },
        subTitle:{
            type:String,
            required:true
        },
        thirdTitle:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        },
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }]
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }]
    },
    fourthSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }],
    },
})

export default mongoose.models.Mice || mongoose.model("Mice", miceSchema);