import mongoose from "mongoose";

const teamSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
        required:true
    },
    metaDescription:{
        type:String,
        required:true
    },
    firstSection:{
        mainTitle:{
            type:String,
            required:true
        },
        subTitle:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        }
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            designation:{
                type:String,
                required:true
            }
        }]
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        firstImage:{
            type:String,
            required:true
        },
        firstImageAlt:{
            type:String,
        },
        secondImage:{
            type:String,
            required:true
        },
        secondImageAlt:{
            type:String,
        },
    },
    fourthSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            logo:{
                type:String,
                required:true
            },
            logoAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }],
    },
})

export default mongoose.models.Team || mongoose.model("Team", teamSchema);