import mongoose from "mongoose";

const uaeSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
        required:true
    },
    metaDescription:{
        type:String,
        required:true
    },
    firstSection:{
        mainTitle:{
            type:String,
            required:true
        },
        subTitle:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        firstImage:{
            type:String,
            required:true
        },
        firstImageAlt:{
            type:String,
        },
        secondImage:{
            type:String,
            required:true
        },
        secondImageAlt:{
            type:String,
        },
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
        }]
    },
    fourthSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
        }],
    },
    fifthSection:{
        title:{
            type:String,
            required:true
        },
        items:[{
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
                required:true
            },
        }]
    }
})

export default mongoose.models.UAE || mongoose.model("UAE", uaeSchema);